server: 
   port: 8080 
   
spring: 
   profiles: 
      active : dev
   
---
spring: 
 profiles: dev
   
 datasource: 
  #url: jdbc:h2:/Users/leisun/Documents/h2Storage;DB_CLOSE_ON_EXIT=FALSE
  #url: jdbc:h2:D:\programs\ELCIPSE\h2Storage;DB_CLOSE_ON_EXIT=FALSE
  #username: sa
  #password: 123456
  #driver-class-name: org.h2.Driver
  
  #mysq8+  conf
  url: jdbc:mysql://172.96.244.235:3306/db?useSSL=false
  username: test
  password: Tmri@2018
  driver-class-name: com.mysql.cj.jdbc.Driver
  
  #
 messages: 
  basename: i18n.login
   
 thymeleaf: 
  cache: false 

 resources: 

  
server:
   port : 8081
   
  
---
spring: 
   profiles: prod

server:
   port : 8082
   
  
    
   
      
      