server: 
   port: 8080 
   
spring: 
   profiles: 
      active : dev
   
---
spring: 
 profiles: dev
   
 datasource: 
  url: jdbc:h2:/Users/leisun/Documents/h2Storage;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: 123456
  driver-class-name: org.h2.Driver

server:
   port : 8081
   
  
---
spring: 
   profiles: prod

server:
   port : 8082
   
  
    
   
      
      